// lib/dashboard/metrics.ts
import type { MetricDefinition } from "@/types/dashboard-metrics";

export const DASHBOARD_METRICS: MetricDefinition[] = [
  // ===== 用戶領域 =====
  {
    key: "total_users",
    label: "系統總用戶數",
    description: "所有內部員工帳號總數",
    category: "users",
    displayType: "NUMBER",
    icon: "Users",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "active_users",
    label: "活躍用戶數",
    description: "啟用中的內部員工",
    category: "users",
    displayType: "NUMBER",
    icon: "UserCheck",
    resolveRelations: [],
    defaultConfig: { filters: { isActive: true } },
  },
  {
    key: "users_by_position",
    label: "各職位人數分布",
    description: "依職位分組的員工數量",
    category: "users",
    displayType: "CHART_PIE",
    icon: "Briefcase",
    resolveRelations: [{ field: "positionId", displayField: "name", model: "Position" }],
    defaultConfig: {},
  },
  {
    key: "users_by_role",
    label: "各角色人數分布",
    description: "依角色分組的員工數量",
    category: "users",
    displayType: "CHART_BAR",
    icon: "Shield",
    resolveRelations: [],
    defaultConfig: {},
  },

  // ===== 專案領域 =====
  {
    key: "active_projects",
    label: "運行中專案",
    description: "狀態為進行中的專案數量",
    category: "projects",
    displayType: "NUMBER",
    icon: "Briefcase",
    resolveRelations: [],
    defaultConfig: { filters: { status: "IN_PROGRESS" } },
  },
  {
    key: "projects_by_status",
    label: "專案狀態分布",
    description: "依狀態分組顯示所有專案",
    category: "projects",
    displayType: "CHART_PIE",
    icon: "PieChart",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "overdue_projects",
    label: "逾期專案",
    description: "超過截止日但未完成的專案",
    category: "projects",
    displayType: "NUMBER",
    icon: "AlertTriangle",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "projects_by_pm",
    label: "各 PM 負責專案數",
    description: "依 PM 分組顯示專案數量",
    category: "projects",
    displayType: "CHART_BAR",
    icon: "UserCircle",
    resolveRelations: [{ field: "pmId", displayField: "name", model: "User" }],
    defaultConfig: {},
  },
  {
    key: "pending_versions",
    label: "待審核版本",
    description: "客戶尚未審核的工作版本",
    category: "projects",
    displayType: "NUMBER",
    icon: "FileClock",
    resolveRelations: [],
    defaultConfig: { filters: { reviewStatus: "PENDING" } },
  },

  // ===== 銷售領域 =====
  {
    key: "total_quotations",
    label: "總報價單數",
    description: "所有報價單總數",
    category: "sales",
    displayType: "NUMBER",
    icon: "FileText",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "win_rate",
    label: "成交率",
    description: "報價成功轉專案的比率",
    category: "sales",
    displayType: "PERCENTAGE",
    icon: "TrendingUp",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "total_quotation_amount",
    label: "總報價金額",
    description: "所有報價單的總金額",
    category: "sales",
    displayType: "NUMBER",
    icon: "DollarSign",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "quotations_by_sales",
    label: "各業務報價排名",
    description: "依業務分組顯示報價數量與金額",
    category: "sales",
    displayType: "CHART_BAR",
    icon: "Award",
    resolveRelations: [{ field: "salesId", displayField: "name", model: "User" }],
    defaultConfig: { sortBy: "count", sortOrder: "desc", limit: 10 },
  },

  // ===== 設備領域 =====
  {
    key: "available_equipment",
    label: "可用設備數",
    description: "狀態為 AVAILABLE 的設備數量",
    category: "equipment",
    displayType: "NUMBER",
    icon: "CheckCircle",
    resolveRelations: [],
    defaultConfig: { filters: { status: "AVAILABLE" } },
  },
  {
    key: "equipment_by_status",
    label: "設備狀態分布",
    description: "依狀態分組顯示所有設備",
    category: "equipment",
    displayType: "CHART_PIE",
    icon: "PieChart",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "equipment_asset_value",
    label: "設備資產總值",
    description: "所有設備的價值總和",
    category: "equipment",
    displayType: "NUMBER",
    icon: "Wallet",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "maintenance_cost",
    label: "本月維修費用",
    description: "本月的維修花費總額",
    category: "equipment",
    displayType: "NUMBER",
    icon: "Wrench",
    resolveRelations: [],
    defaultConfig: { dateRange: "THIS_MONTH" },
  },
  {
    key: "overdue_equipment_logs",
    label: "逾期未還設備",
    description: "超過預計歸還日仍未歸還的設備",
    category: "equipment",
    displayType: "LIST",
    icon: "AlertCircle",
    resolveRelations: [
      { field: "equipmentId", displayField: "name", model: "Equipment" },
      { field: "borrowedById", displayField: "name", model: "User" },
    ],
    defaultConfig: { limit: 10 },
  },

  // ===== 任務領域 =====
  {
    key: "staff_todo_completion_rate",
    label: "待辦事項完成率",
    description: "員工待辦事項的完成比例",
    category: "tasks",
    displayType: "PERCENTAGE",
    icon: "CheckSquare",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "overdue_todos",
    label: "逾期待辦",
    description: "超過目標日期仍未完成的待辦",
    category: "tasks",
    displayType: "NUMBER",
    icon: "Clock",
    resolveRelations: [{ field: "staffId", displayField: "name", model: "User" }],
    defaultConfig: {},
  },

  // ===== 客戶領域 =====
  {
    key: "total_customers",
    label: "總客戶數",
    description: "所有客戶帳號總數",
    category: "customers",
    displayType: "NUMBER",
    icon: "Building2",
    resolveRelations: [],
    defaultConfig: {},
  },
  {
    key: "pending_collaboration_requests",
    label: "待處理合作申請",
    description: "尚未處理的合作申請數量",
    category: "customers",
    displayType: "NUMBER",
    icon: "MailQuestion",
    resolveRelations: [],
    defaultConfig: { filters: { status: "PENDING" } },
  },
];
